Check if required commands exist at startup

diff --git a/ppget b/ppget
--- a/ppget
+++ b/ppget
@@ -39,6 +39,37 @@ pirateplay() {
 	curl -Ss "$APIURL$1" || exit 1
 }
 
+# implementing my own which because I can't get
+# the regular one to not print error messages
+which() {
+	IFS=$':'
+	exists=$(for p in $PATH; do
+		if [ -x "$p/$1" ]; then
+			echo yes
+			break
+		fi
+	done)
+	unset IFS
+
+	test "$exists" && return 0
+	return 1
+}
+
+checkcommands() {
+	needed=$(
+	for p in $@; do
+		which $p || echo $p
+	done)
+
+	if [ "$needed" ]; then
+		echo "The following commands are missing from your \$PATH:"
+		echo $needed | tr ' ' '\n'
+		return 1
+	fi
+
+	return 0
+}
+
 selquality() {
 	# XXX: I'm assuming higher number is better quality
 	awk -v "quality=$1" '
@@ -158,6 +189,8 @@ elif [ $# -eq 2 ] || [ $# -eq 3 ]; then
 else
 	usage $(basename $0)
 fi
+
+checkcommands jshon curl ffmpeg rtmpdump || exit 1
 
 if [ "$list" ]; then
 	pirateplay "$url" | jshon -C -a -e meta -e quality -u -p -e suffixHint -u | \
